version: '3'

services:
  database:
    build: ./docker/database
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  database:
